### PR TITLE
cleanup: peform a noop in case of a failed command

### PR DESCRIPTION
**Pull request by MaximilianMeister**
otherwise the next one won't be executed

Signed-off-by: Maximilian Meister <mmeister@suse.de>

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
we want to still clear the directory when this happens:

```
>>> Cleaning up old containers
"docker rm" requires at least 1 argument(s).
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
kubelet: no process found
```

**Comment by PI-Victor** [comment]
see my comment here: https://github.com/kubic-project/velum/pull/104#discussion_r108974797

**Comment by MaximilianMeister** [comment]
> see my comment here: kubic-project/velum#104 (comment)

thanks for the hint, i guess we can remove the noop again once this is addressed in `velum`

**Comment by MaximilianMeister** [comment]
rebased

**Pull request merged**
